on: [pull_request, workflow_dispatch]
name: terraform fmt
permissions:
  contents: write
jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run fmt
        run: terraform fmt
      - name: commit and push
        run: |
          git config --global user.email "automatic@email.com"
          git config --global user.name "automatic pr"
          git fetch
          git add *.tf
          git commit -m 'automatic fmt'
          echo "git push origin ${{ github.head_ref }}"
