on: [pull_request, workflow_dispatch]
name: terraform fmt

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run fmt
        run: terraform fmt
      - name: commit and push
        run: |
          git add *.tf
          git commit -m 'automatic fmt'
          git push
